#!/bin/sh
uppomf="https://comfy.moe/upload.php"

if test $# -lt 1; then
	echo "Usage $(basename "$0") FILE [FILE...]"
	exit 1
fi

set=
for f; do
	test "$set" || set -- ; set=1
	set -- "$@" -F "files[]=@$f"
done

curl -L "$@" "$uppomf" | jq -c -r ".files[].url"
